version: '3'
services:
  # db is is db folder
  db:
    image: devopsgroup4.azurecr.io/db
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"

  # Application Dockerfile is in same folder which is .
  app:
    image: devopsgroup4.azurecr.io/app
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run

# Nginx Docker file is in web folder
  nginx:
    image: devopsgroup4.azurecr.io/nginx
    build: web/.
    ports:
      - "80:80"
